INSERT INTO Drivers (first_name, last_name, car_number, irl_affiliation) VALUES
('Max', 'Verstappen', 1, 'Red Bull'),
('Liam', 'Lawson', 30, 'Red Bull'),
('Lewis', 'Hamilton', 44, 'Ferrari'),
('Charles', 'Leclerc', 16, 'Ferrari'),
('George', 'Russell', 63, 'Mercedes'),
('Andrea Kimi', 'Antonelli', 12, 'Mercedes'),
('Lando', 'Norris', 4, 'McLaren'),
('Oscar', 'Piastri', 81, 'McLaren'),
('Fernando', 'Alonso', 14, 'Aston Martin'),
('Lance', 'Stroll', 18, 'Aston Martin'),
('Pierre', 'Gasly', 10, 'Alpine'),
('Jack', 'Doohan', 7, 'Alpine'),
('Alex', 'Albon', 23, 'Williams'),
('Carlos', 'Sainz', 55, 'Williams'),
('Yuki', 'Tsunoda', 22, 'Racing Bulls'),
('Isack', 'Hadjar', 6, 'Racing Bulls'),
('Nico', 'Hulkenberg', 27, 'Sauber/Audi'),
('Gabriel', 'Bortoleto', 5, 'Sauber/Audi'),
('Oliver', 'Bearman', 87, 'Haas'),
('Esteban', 'Ocon', 31, 'Haas');
